### ISSUE TITLE
Download jq binary for platform (win32)...

### ISSUE THREAD

**Issue by viveksharma2175** [davidnussio/vscode-jq-playground#25] opened 2019-08-06 01:38 UTC
Not sure how to fix this. I am getting this in output window

**Comment by davidnussio** [comment] 2019-08-06 15:48
Do you get this message every time start vscode with a jq file?

I think the problem is that the binary is saved to the extensions's directory and this one is removed when the extension is updated. Then, after the update, the extension doesn't find the binary and download it.

**Comment by viveksharma2175** [comment] 2019-08-07 03:10
Yes I get it every time. And I am not sure if it does anything after this. It just sits there with this message in the output console.

**Comment by davidnussio** [comment] 2019-08-08 15:39
I guess the problem is with the checksum of binary, it doesn't match and download it again.
This check is used to update jq when a new version is released.
I didn't get this problem on linux, will check on windows.
Do you have spaces into your home directory path?

**Comment by viveksharma2175** [comment] 2019-08-09 06:12
There are no spaces in the home directory path. 
I checked the extension.js file. The bin folder its referring to is empty.

**Comment by davidnussio** [comment] 2019-08-09 15:46
Ok, something fails before calculate the checksum.
The candidate is the code that download the jq binary
https://github.com/davidnussio/vscode-jq-playground/blob/3d20be36418169207c3c7b883de3c85b662b9a36/src/extension.ts#L166-L174

I checked the issues of the download package and someone has problems using vpn... but I don't know...

Sure, I should add code to catch the error.
Maybe, I could will add settings to overwrite the path of jq binary and let users use which jq version wants.

I already changed the code to save jq binary into globalStoragePath instead of extension directory itself.

If you want test the download code:

1. npm init -y
2. npm install download
3. copy code (https://gist.github.com/davidnussio/9ef8f86d837c79b3e1ed1fe86c038f9e)

Thank you

**Comment by davidnussio** [comment] 2019-08-10 06:20
I was able to test on Windows 10 machine but it is working. Antivirus or some kind of system protection?

**Comment by viveksharma2175** [comment] 2019-08-10 11:58
I am behind a proxy. Would that cause an issue??

**Comment by davidnussio** [comment] 2019-08-10 17:24
The node library that I use to download has this open issue [Support proxies #64](https://github.com/kevva/download/issues/64)

**Comment by davidnussio** [comment] 2020-04-26 19:20
![2020-04-26_21-16](https://user-images.githubusercontent.com/324371/80317295-47da7500-8803-11ea-8708-b1eaa78d13d4.png)

As workaround I added the possibility to manually download the binary and set path into configuration. 
It is going to be released with the next update

**Comment by dsielert** [comment] 2020-05-14 18:16
@davidnussio  I set the binary path per this but it's still trying to download it

**Comment by dsielert** [comment] 2020-05-14 18:18
![image](https://user-images.githubusercontent.com/46495289/81970581-9b570c00-95d4-11ea-92ae-362bc436c300.png)

**Comment by davidnussio** [comment] 2020-05-14 21:11
Ok, I found out the problem with binaryPath configuration. Sorry, I'm going to fix it!
Are you behind to a proxy?

**Comment by dsielert** [comment] 2020-05-15 15:44
seems like you pushed the fix! thanks !

**Comment by davidnussio** [comment] 2020-05-15 15:57
Thanks to you for the feedback.

**Closed by davidnussio** 2020-05-15 15:57 UTC
Labels: bug
